### ISSUE TITLE
Data registration page is missing info box

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#106]
Data registration page is missing info box with explanatory text like on module config page

**Comment by uleopold** [comment]
Matteo, can you paste a similar info box at the top of the "Data Registration" page such as the blue box at the "Module Configuration" page.

![selection_241](https://cloud.githubusercontent.com/assets/1353359/6146073/0f98bdf0-b1e9-11e4-927e-c0f0deefbfcd.png)
