### ISSUE TITLE
Module results are not being listed in the web interface

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/iguess#153]
I ran the Dijkstra Van process in the LaMiLo site and got a success message back. A new dataset is now registered in the database with the name "LdS.ShortestPathVan02", but it is not showing up in the Data Manager, nor in the Maps.

**Comment by uleopold** [comment]
Can this issue be closed or is it still occuring?

**Comment by ldesousa** [comment]
I was able to identify part of the issue regarding this particular layer: when I access the Data Manager the layers listed are from Luxembourg, not Aberdeen. This seems to be another feature of the user management system currently in place.

What is yet to explain is why a layer generated with Luxembourg inputs ended up registered in Aberdeen.

**Comment by uleopold** [comment]
I think, you need to pay attention that you have selected the correct 
city before you configure and run a module. Sometimes the city is only 
switched when you have first reloaded the page and then switch to the 
city, else it might still show data layers from other cities.

I agree that the user management seems a bit messy at the moment.


On 23/03/15 11:22, Luís de Sousa wrote:
>
> I was able to identify part of the issue regarding this particular 
> layer: when I access the Data Manager the layers listed are from 
> Luxembourg, not Aberdeen. This seems to be another feature of the user 
> management system currently in place.
>
> What is yet to explain is why a layer generated with Luxembourg inputs 
> ended up registered in Aberdeen.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ERIN-LIST/iguess/issues/153#issuecomment-84934555>.
>

-- 
Ulrich Leopold
Senior Researcher in Geocomputation

eScience Unit
Department for Environmental Research and Innovation (ERIN)
Luxembourg Institute of Science and Technology (LIST)

Room D1.06
41, Rue du Brill,
L-4422 Belvaux
Luxembourg

tel: +352 425991 4618
mobile: +352 691 304813
email: ulrich.leopold@list.lu
http://www.list.lu/erin

**Comment by ldesousa** [comment]
The configuration registration in a different city is also a feature of the present user management system. Under certain conditions, iGUESS uses whatever is in the proxy set in the user's system, disregarding what is selected in the dropdown box.

Since this behaviour seems to have been coded wittingly, I am closing this issue.
