### ISSUE TITLE
Scenario tool - Toggle units is missing for Energy Production

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/iguess#195]
Th etoggle units button is missing for energy production. I am not sure if this was ever there. But it is of course necessary as only one toggle button does not make sense. 

This  way we can fill MWh directly for the start year and do not need import data. Later we can develop an upload button for tables if that is necessary.

Rui can you confirm this need?

**Comment by ldesousa** [comment]
A basic version of this functionality was implemented with merge 4cb7208904c3ec8009e7651d732d7cda75ace1cd. Since there have been no complaints I am closing the issue.
