### ISSUE TITLE
WCS: parsing of SRS description in DescribeCoverage

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#213]
We have the problem that WCS (GeoServer) of Ghent can not be properly registered because of missing SRS description in GetCapabilities. We have been assuming in the passed that MapServer delivers standard conformity of the request. According to OGC specs about the WCS standard the assumption is wrong. SRS does not need to be specified in GetCapabilities. Therefore, DescribeCoverage needs to be parsed to get the correct (and mandatory) announcement of the SRS.
The SRS is needed to put together the GetCoverage request in the right form.

Luis should investigate about the general workload and feasibility to hand over to Matteo

**Comment by ldesousa** [comment]
The mass_import code is already taking into account the need for the DescribeCoverage. However, OpenLayers is issuing an exception when parsing the DescribeCoverage response from Gent.
