### ISSUE TITLE
OMP results are not being stored

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/iguess#217]
The OMP process runs correctly and iGUESS reports the success message. But in the Data Manager the resulting dataset is not present. It is not registered in the data base either.

**Comment by uleopold** [comment]
We have the same issue already registerd #153 with another routing module. Please consult issue #153  and see if this one can be closed.

**Comment by ldesousa** [comment]
The configuration named "LdS.Lux.OMP.2" reports the following status location: http://wps.iguess.tudor.lu/wpsoutputs/pywps-b939c15e-addb-11e4-8128-005056a52e0d.xml

The status location reports the following result location: http://wps.iguess.tudor.lu/wpsoutputs/omp_paths-b939c15e-addb-11e4-8128-005056a52e0d.gml

But the results contains the following:
<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://schemas.opengis.net/gml/2.1.2/feature.xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml">
  <gml:boundedBy><gml:null>missing</gml:null></gml:boundedBy>                                                                                          
</ogr:FeatureCollection>

Things to check:
. Is the file in the wps server?
. Exceptions in the log files (PyWPS, Apache)
. Disk space

**Comment by ldesousa** [comment]
I can replicate this issue directly from the WPSClient. This is either a problem with the process or with PyWPS itself.
