### ISSUE TITLE
BBOX parameter of WCS processed by WPS is switched

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#225]
The request BBOX x,y parameter of a layer derived by WCS calculated by our WPS (e.g. Ludwigsburgs 00_solar_irradiation_02) is switched.
We had issues like this constantly...

The mapfile seems to be correct. Probably an issue about how the request is put together form variables in the database.
![screen shot 2015-02-10 at 16 25 20](https://cloud.githubusercontent.com/assets/2735053/6129830/6ce16a46-b141-11e4-9d84-646f49144872.png)

**Comment by christianbraun** [comment]
tracked down to mass_import, just happens (as discovered so far) for Ludwigsburg data sets

**Comment by ldesousa** [comment]
The DescribeCoverage response in version 1.0.0 is ambiguous, neither the mass_import nor the harvester are able to determine grid resolution properly. For instance this request:

http://maps.iguess.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/ES_localOWS.map&SERVICE=WCS&VERSION=1.0.0&REQUEST=DescribeCoverage&COVERAGE=elevation

Returns this information:

<gml:offsetVector>100 0</gml:offsetVector>
<gml:offsetVector>0 -100</gml:offsetVector>

Whereas this request:

http://maps.iguess.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/ES_localOWS.map&SERVICE=WCS&VERSION=1.0.0&REQUEST=DescribeCoverage&COVERAGE=elevation

Return this:

<GridOffsets>100 -100</GridOffsets>

I prefer to stick with version 1.1.0 for now and try to resolve this issue some other way.
