### ISSUE TITLE
Not possible to stop module run after WPS raised an error and failed

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#226]
After starting the UHI module it failed due to pywps error of not getting data from remote server. the module doesn't seem to catch this pywps error and is running further. stop button is not working.
module config needs to be deleted.

however, the pywps error is identified and fixed.
PyWPS [2015-02-11 11:23:59,242] INFO: Status [processfailed]: Remote server says: [http://mapservices-aberdeen.tudor.lu/aberdeen_ows&SERVICE=WCS&FORMAT=image/img&BBOX=392832,806038,395110,810319&RESX=30&RESY=30&RESPONSE_CRS=EPSG:27700&CRS=EPSG:27700&VERSION=1.0.0&REQUEST=GetCoverage&COVERAGE=AB_ls5] not found

http://iguess.tudor.lu/mod_configs/331
![screen shot 2015-02-11 at 11 31 31](https://cloud.githubusercontent.com/assets/2735053/6145391/a1d3f9bc-b1e1-11e4-9b65-0a86c0ee8a9a.png)

**Comment by ldesousa** [comment]
The module status is not being correctly updated in the database. However, there are 3 different fields in the mod_configs table for the status:
. status
. status_text
. run_status_id
To fix this issue I must figure out what each of these fields are. I've contacted Chris for help.
