### ISSUE TITLE
Area of Interest does not work with WFS 1.1.0 and WCS

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/iguess#235]
Once the WFS 1.1.0 milestone is finished, all vector layers registered in iGUESS will have their bounding boxes stored in the WGS84 CRS (EPSG:4326). Up to now these bounding boxes were used as areas of interest to limit module calculations in space.

Since for raster layers the bounding box provided to the WCS must be in the original CRS, the new WFS 1.1.0 bounding boxes no longer work.

There are two possible fixes:

a) De-activate the area of interest.

b) Project vector bounding boxes between WGS84 and the original system. This requires Rails to use something like proj. No idea at this stage how to do is in a simple way

**Comment by uleopold** [comment]
Option a is not possible. We should discuss the WFS 1.1.0 implementation more in detail to see how it affects this issue and what can be the solutions also regarding WFS 1.1.0 implementations.

**Comment by ldesousa** [comment]
Fixed with merge 45e64c9b8b67c612d233fb6df73c5f3d88a87a3e.
