### ISSUE TITLE
WCS BBox in WGS84: datasets controller

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/iguess#244]
Make sure the BBox CRS (WGS84) and the calculation CRS (city CRS) are correct.

**Comment by ldesousa** [comment]
I am composing the GetCoverage request as I did for GetFeatures, but MapServer is struggling with it.

This format is not supported:
http://iguess-mapserv.kirchberg.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LUX_samples.map&SERVICE=WCS&VERSION=1.1.0&REQUEST=GetCoverage&IDENTIFIER=LuxProtectedAreas&FORMAT=image/tiff&CRS=EPSG:2169&RESX=86.3928319642818&RESY=86.3928319642818&BOUNDINGBOX=49.4628933953496,5.90435442673963,49.6892195720654,6.24077598688919,urn:x-ogc:def:crs:EPSG:4326

With this one there is a BBox error:
http://iguess-mapserv.kirchberg.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LUX_samples.map&SERVICE=WCS&VERSION=1.1.0&REQUEST=GetCoverage&IDENTIFIER=LuxProtectedAreas&FORMAT=image/tiff&CRS=EPSG:2169&RESX=86.3928319642818&RESY=86.3928319642818&BOUNDINGBOX=49.4628933953496,5.90435442673963,49.6892195720654,6.24077598688919,EPSG:4326

Christian: could you please a GetCoverage request that functions correctly with MapServer and Geoserver, as you did for WFS?

**Comment by uleopold** [comment]
Below is a valid request for the first format you mention above. I am just not so sure if the result is actually  correct. Maybe Christian can check and improve.

http://iguess-mapserv.kirchberg.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LUX_samples.map&SERVICE=WCS&VERSION=1.1.0&REQUEST=GetCoverage&IDENTIFIER=LuxProtectedAreas&FORMAT=image/tiff&CRS=EPSG:2169&BOUNDINGBOX=49.47,5.91,49.67,6.23,urn:ogc:def:crs:EPSG::4326

**Comment by ldesousa** [comment]
Ulli, this request is missing the resolution parameters, I believe this can not be used to feed the modules. I will test it again tomorrow.

**Comment by uleopold** [comment]
This request does not work either but is more complex and trying to follow WCS 1.1.0 specifications.

http://iguess-mapserv.kirchberg.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/iGUESSMapFiles/RO_solar_irradiation.map&
SERVICE=WCS&
VERSION=1.1.0&
REQUEST=GetCoverage&
IDENTIFIER=solar_irradiation&
FORMAT=image/img&
BOUNDINGBOX=51.9149915640524,4.47461319308816,51.9161122237375,4.47655274238612,urn:ogc:def:crs:EPSG::4326&
GridBaseCRS=urn:ogc:def:crs:EPSG::28992&
GridCS=urn:ogc:def:crs:EPSG::28992&
GridType=urn:ogc:def:method:WCS:1.1:2dGridIn2dCrs&
GridOrigin=92213,436672&
GridOffsets=0.5,0.5

**Comment by ldesousa** [comment]
From the response to this request:

http://iguess-mapserv.kirchberg.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LUX_samples.map&
SERVICE=WCS&
VERSION=1.1.0&
REQUEST=GetCoverage&
IDENTIFIER=LuxProtectedAreas&
FORMAT=image/img&
BOUNDINGBOX=49.4628933953496031,5.9043544267396300,49.6892195720653973,6.2407759868891901,urn:ogc:def:crs:EPSG::4326&
GridCS=urn:ogc:def:crs:EPSG::2169

Is seems MapServer is struggling to reproject the BBox; note how the reported coordinates are equal for both corners.

**Comment by christianbraun** [comment]
We decided to NOT use GetCoverage with VERSION=1.1.0! This is resulting in very long complicated requests and anyway in a different multi-MIME format which can not be processed easily.
As I understood, this issue with the request is happening for the harvester. The harvester is not in need of GetCoverage, thus a GetCapabilities and DescribeCoverage in Version 1.1.0 could be used to get the necessary information about the datasets.

http://iguess-mapserv.kirchberg.tudor.lu/ro_ows?
SERVICE=WCS&
VERSION=1.1.0&
REQUEST=DescribeCoverage

Does this help???

**Comment by ldesousa** [comment]
All points to a bug with Mapserver treating the GetCoverage request in version 1.1.0; it seems unable to convert the WGS84 BBox to the native system and issues false errors.

However, it functions properly with version 1.0.0, in a format like:
http://iguess-mapserv.kirchberg.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LUX_samples.map&
SERVICE=WCS&
FORMAT=image/img&
BBOX=5.9451,49.49034,5.98407,49.50304&
RESX=86.3928319642818&
RESY=86.3928319642818&
RESPONSE_CRS=EPSG:2169&
CRS=urn:x-ogc:def:crs:EPSG:4326&
VERSION=1.0.0&
REQUEST=GetCoverage&
COVERAGE=LuxProtectedAreas

The main differences to WFS are:
. coordinates defined in lon-lat, instead of lat-lon
. BBox CRS expressed in its own parameter

The datasets controller is already building request this way, no further coding is necessary.

iGUESS still uses different versions of the standard for different requests:
1.1.0 - GetCapabilities & GetCoverage
1.0.0 - GetCoverage

This might prove a source of other issues, but I am closing this issue in any case to complete this milestone.
