### ISSUE TITLE
Is harvester reporting unavailable datasets correctly?

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/iguess#246]
The harvester reports datasets to be unavailable (production version). In fact the datasets are available as WMS and WCS. Though, WCS is only available as WGS84.
http://wms.isric.org/geoserver/wms

![selection_266](https://cloud.githubusercontent.com/assets/1353359/6570324/b38de060-c6f8-11e4-8401-e0bc2359b12d.png)

When using the URL above for dataset registration the above datasets show up as available WMS and WCS. Though, WCS is only available as WGS84 projection. So maybe the Harvester reports status unavailable because of different WCS projection although WMS is available and WCS only in a different projection?

![selection_267](https://cloud.githubusercontent.com/assets/1353359/6570346/41faf8ce-c6f9-11e4-9f7c-7678e141bf12.png)

On the meta data sheet iGUESS gives an even more misleading message: 

"**This layer is no longer available -- the data owner may have renamed or removed it. Sorry!**"

But WMS and WCS should be both available.

![selection_268](https://cloud.githubusercontent.com/assets/1353359/6571004/8652a1b6-c703-11e4-992d-baff08c459ff.png)

**Comment by ldesousa** [comment]
I tested various datasets marked as unavailable in the Atlas. For all these the server is replying with an exception, thus I think the messages reported by the Harvester (and the Rails application) are correct.
