### ISSUE TITLE
Gent WFS 1.1.0 not correctly reported in meta data pop up --> No tags are possible 

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/iguess#254]
The Metadata popup window does not report Gent WFS data sets. It only reports WMS. Check for example layer Gent Ara of Interest (GE_aio). Click the gear and you will see only WMS no WFS although the request below shows WFS available. This makes it impoossile to tag data sets for Gent currently.

Here the request from the WFS MetaData pop up which is correct. 
http://mapservices-gent.tudor.lu/gent_ows?&SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities

![selection_271](https://cloud.githubusercontent.com/assets/1353359/6684784/be0940ec-cc94-11e4-8f33-eb7810732543.png)

**Comment by ldesousa** [comment]
This seems to be the harvester.py. In iGUESS the layer is being registered correctly.

**Comment by ldesousa** [comment]
This problem was created by a bug with OWSLib. Fixed here:
https://github.com/ldesousa/OWSLib/commit/a200dc9c51fac29dacedfc3ec6118798ed6d5cc6
