### ISSUE TITLE
WFS 1.1.0 data request issues for Ludwigsburg

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#257]
Mapserver is reporting back data in yx axis order. This breaks overlay of layers in GRASS and thus modules for LB are not working. It seems very likely will not solve this until the meeting next week!

Seems to be a Mapserver bug because same requests for Geoserver are working and returning xy order. I wrote to the list already. Lets see what they will answer.

Possible solutions? Not many. 1.0.0 for WFS is not working with the redesigned the data request system. Maybe a change of the default local projection...

**Comment by uleopold** [comment]
There are many bugs in map server it seems. Maybe we should consider an upgrade of map server at some point. 

In the meantime I hope we can find a workaround until next week.

**Comment by christianbraun** [comment]
I was testing it with 6.4.1 without success.
Updates are not the overall solution, Uli.

I am in constant exchange with Luis about this and we don't want to break overall iGUESS functionality before the meeting.
We have to wait for the answers of the different lists...

**Comment by uleopold** [comment]
I did not say before the meeting, only in the future after the meeting. But we came across acouple of bugs in mapserver so maybe an upgrade can help in the future.

For next week we need a workaround not an upgrade.

**Comment by uleopold** [comment]
Is it true that this is only specific to Ludwigsburg? If so it must be a problem of the local projection, maybe proj or something else which reprojects the data incorrectly?

If a general bug in mapserver it would mean that all other Mapserver WFS data services for the other cities we have set up (Rotterdam, Gent) would fail too, right?

Have you tried for other cities (Gent, Rotterdam)? And if yes what was the result?

**Comment by christianbraun** [comment]
don't worry, it is fixed

**Comment by christianbraun** [comment]
due correct to interpreting of axis order for EPSG:31467. Switched LB local SRS to EPSG:25832
