### ISSUE TITLE
WCS of Gent Geoserver is not parsed at all at "Register datasets" Page

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#259]
Working WCS implementation by Gent
http://extragisqa.gent.be/geoserver/Gent/ows?service=wcs&version=1.1.0&request=GetCapabilities

Not a single layer is shown as WCS, just WMS

**Comment by ldesousa** [comment]
The service is answering back to the DescribeCoverage request with an exception:

<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://extragisqa.gent.be/geoserver/schemas/ows/1.1.0/owsAll.xsd">
  <ows:Exception exceptionCode="MissingParameterValue" locator="identifiers">
    <ows:ExceptionText>Required paramer, identifiers, missing</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>

**Comment by ldesousa** [comment]
iGUESS is issuing DescribeCoverage requests without specifying coverage identifiers. Although this formulation works with MapServer, in the standard it is clearly stated that this parameter is mandatory.

Fixing this issue requires a good dose of re-working in the mass_import.

**Comment by uleopold** [comment]
Can we not simply add this parameter to the WCS DescribeCoverage requests?

**Comment by ldesousa** [comment]
You can not simply add the parameter, you must mast also pass an argument. Therein lies the difficulty.

**Comment by ldesousa** [comment]
I have drafted a new implementation of the mass_import view that works in two steps: first sends a GetCapabilities and then a DescribeCoverage with all the coverage identifiers. However, GeoServer is returning a response document with version 1.1.1 that OpenLayers is not able to read.  

The request is being sent with version 1.1.0, so GeoServer should response back with the same version.

**Comment by ldesousa** [comment]
According to Andrea Aime GeoServer does not support WCS 1.1.0:
http://osgeo-org.1560.x6.nabble.com/Response-to-WCS-1-1-0-DescribeCoverage-td5196443.html
