### ISSUE TITLE
Front page not showing properly

### ISSUE THREAD

**Issue by rfmartins** [ERIN-LIST/iguess#263]
In my screen this is how the home page looks!
![screenshot](https://cloud.githubusercontent.com/assets/8504260/6965297/b062e524-d950-11e4-8e76-2d04cfa7b648.png)

**Comment by christianbraun** [comment]
I find it also too big in text size and screen shots are in very very poor quality. Overall it is taking too much of vertical space

**Comment by ldesousa** [comment]
I have testes with Chromium, Firefox, Opera and IExplorer but I could not replicate this problem.
