### ISSUE TITLE
Mass Import is not able to assign processing tag to GeoServer WCS

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#264]
![screen shot 2015-04-23 at 09 44 24](https://cloud.githubusercontent.com/assets/2735053/7292566/704e9cfa-e99d-11e4-8b2a-3fa999705644.png)

**Comment by christianbraun** [comment]
but works with data manager and gear icon

**Comment by ldesousa** [comment]
This is working now. Possibly a consequence of the things I am trying on issue #265.
