### ISSUE TITLE
WFS not working correctly in mass import - data set not available for processing

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/iguess#274]
WFS shows data sets unavailable although they are in the correct projection. Could you check if it is working correctly? This seems to happen when I reload the mass_import URL a few times. Sometimes it is shown correctly and sometimes it is showing unavailable.

Some kind of random behaviour. I tested in the production and the test version. The appearance and behaviour is similar as in issue  #273.

**Comment by ldesousa** [comment]
Can you please post here a server URL with which this is happening? I can not replicate this behaviour.

**Comment by uleopold** [comment]
I cannor reproduce it any longer either. So I close it.
