### ISSUE TITLE
Data manager does not display web server name for aberdeen

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/iguess#51]
The server name is empty for  WCS data set from Aberdeen. See screenshot below:

![selection_063](https://cloud.githubusercontent.com/assets/1353359/3268211/7ff724da-f2d9-11e3-9b4c-ed9ac930f39e.png)

**Comment by ldesousa** [comment]
This is a bug with ESRI software. Aberdeen is setting up MapServer and/or Geoserver.
