### ISSUE TITLE
Harmonize version numbers in requests

### ISSUE THREAD

**Issue by christianbraun** [ERIN-LIST/iguess#74]
WCS data should is requested in 1.0.0. WCS Get Capabilities is asked for in 1.0.0.
Harmonize all this requests.

![screen shot 2014-06-20 at 10 42 11](https://cloud.githubusercontent.com/assets/2735053/3338158/f1cd6470-f856-11e3-8ec6-42806d9f2ea0.png)

**Comment by ldesousa** [comment]
iGUESS now uses (mostly) WCS 1.1.1 .
